insurer= CARRIER,CONSUMER,
insured= CARRIED, PREPARED FOR, CLAIMANT,
valued date= AS OF,
loss date = DATE OF LOSS, LOSS DATE,
reported date = DATE REPORTED,
status = STATUS,
expense reserve= EXPENSE RESERVE,
expense paid= EXPENSE PAID,
indemnity reserve= INDEMNITY RESERVE,
indemnity paid= INDEMNITY PAID,
report date = RPT DATE, 
broker = BROKER,
expense payments = EXPENSE PAYMENTS,

