insurer = CARRIER, INSURER, ENTITY NAME,
policy_num = POLICY NUMBER, POL NBR, DCN, POLICY
claimant = CLAIMANT NAME, CLAIMANT, NAMED INSURED, SUBJECT NAME, INSURED,
status = STATUS, STUS,
report_date = AS OF, REPORT DATE, DATE OF REPORT,
